name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: your-aws-region

    - name: Install Terraform
      run: |
        wget https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_amd64.zip
        unzip terraform_0.14.5_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

    - name: Terraform Init and Apply
      run: |
        cd infrastructure
        terraform init
        terraform apply -auto-approve

    - name: Deploy Lambda Function
      run: |
        cd lambda
        aws lambda update-function-code --function-name ExampleLambdaFunctionName --s3-bucket testnatwestgroup222 --s3-key ExampleLambdaZipFile.zip

    - name: Deploy EC2 Instance
      run: |
        cd infrastructure
        terraform init
        terraform apply -auto-approve

    - name: Run Tests
      run: |
        curl http://<ec2-public-ip>

    - name: Deploy to S3
      run: |
        cd infrastructure
        terraform init
        terraform apply -auto-approve
